"""Build historical area × industry evidence without forecasting future sales."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd

from src.data.config import generate_quarters, load_datasets_config
from src.utils.paths import INTERIM_DIR, OUTPUT_DIR, PROCESSED_DIR, PROJECT_ROOT

KEYS = ["area_code", "industry_code"]
PANEL_KEYS = ["quarter", *KEYS]
RECENT_QUARTERS = ["20251", "20252", "20253", "20254"]
PREVIOUS_QUARTERS = ["20241", "20242", "20243", "20244"]


@dataclass(frozen=True)
class EvidenceResult:
    """Tables generated by :func:`build_area_industry_evidence`."""

    evidence: pd.DataFrame
    dictionary: pd.DataFrame
    validation: pd.DataFrame
    stale_combinations: pd.DataFrame


def ratio_or_nan(numerator: pd.Series, denominator: pd.Series) -> pd.Series:
    """Divide where both values exist and denominator is positive; otherwise NaN."""
    num = pd.to_numeric(numerator, errors="coerce")
    den = pd.to_numeric(denominator, errors="coerce")
    result = pd.Series(np.nan, index=num.index, dtype="float64")
    valid = num.notna() & den.notna() & den.gt(0)
    result.loc[valid] = num.loc[valid] / den.loc[valid]
    return result.replace([np.inf, -np.inf], np.nan)


def _require_columns(frame: pd.DataFrame, columns: Iterable[str], dataset: str) -> None:
    missing = [column for column in columns if column not in frame]
    if missing:
        raise ValueError(f"[{dataset}] 필요한 컬럼이 없습니다: {missing}")


def _assert_unique(frame: pd.DataFrame, keys: list[str], dataset: str) -> None:
    duplicate_rows = int(frame.duplicated(keys, keep=False).sum())
    if duplicate_rows:
        raise ValueError(f"[{dataset}] {keys} 중복 행: {duplicate_rows:,}")


def _clip_series(
    series: pd.Series,
    *,
    lower_quantile: float,
    upper_quantile: float,
    hard_lower: float | None = None,
    hard_upper: float | None = None,
) -> tuple[pd.Series, pd.Series, tuple[float, float]]:
    """Quantile-clip a series, returning values, changed flags, and bounds."""
    valid = series.dropna()
    if valid.empty:
        return series.copy(), pd.Series(0, index=series.index, dtype="int8"), (np.nan, np.nan)
    lower = float(valid.quantile(lower_quantile))
    upper = float(valid.quantile(upper_quantile))
    if hard_lower is not None:
        lower = max(lower, hard_lower)
    if hard_upper is not None:
        upper = min(upper, hard_upper)
    if lower >= upper:
        lower, upper = float(valid.min()), float(valid.max())
    clipped = series.clip(lower=lower, upper=upper)
    changed = (series.notna() & clipped.ne(series)).astype("int8")
    return clipped, changed, (lower, upper)


def _weighted_store_priors(stores: pd.DataFrame) -> pd.DataFrame:
    """Calculate industry-quarter priors for smoothed store rates."""
    work = stores.copy()
    store_count = pd.to_numeric(work["SIMILR_INDUTY_STOR_CO"], errors="coerce").fillna(0).clip(lower=0)
    work["store_count"] = store_count
    work["franchise_count"] = pd.to_numeric(work["FRC_STOR_CO"], errors="coerce").fillna(0).clip(lower=0)
    work["opening_weighted"] = store_count * pd.to_numeric(work["OPBIZ_RT"], errors="coerce").fillna(0).div(100).clip(0, 1)
    work["closing_weighted"] = store_count * pd.to_numeric(work["CLSBIZ_RT"], errors="coerce").fillna(0).div(100).clip(0, 1)
    prior = work.groupby(["quarter", "industry_code"], observed=True, sort=False).agg(
        prior_store_count=("store_count", "sum"),
        prior_franchise_count=("franchise_count", "sum"),
        prior_opening_weighted=("opening_weighted", "sum"),
        prior_closing_weighted=("closing_weighted", "sum"),
    ).reset_index()
    prior["franchise_prior"] = ratio_or_nan(prior["prior_franchise_count"], prior["prior_store_count"]).fillna(0)
    prior["opening_prior"] = ratio_or_nan(prior["prior_opening_weighted"], prior["prior_store_count"]).fillna(0)
    prior["closing_prior"] = ratio_or_nan(prior["prior_closing_weighted"], prior["prior_store_count"]).fillna(0)
    return prior[["quarter", "industry_code", "franchise_prior", "opening_prior", "closing_prior"]]


def _sales_per_store_priors(panel: pd.DataFrame) -> pd.DataFrame:
    """Calculate observed industry-quarter sales-per-store priors."""
    observed = panel.loc[
        panel["sales_observed"].eq(1) & panel["store_count"].gt(0),
        ["quarter", "industry_code", "quarterly_sales", "store_count"],
    ]
    prior = observed.groupby(["quarter", "industry_code"], observed=True, sort=False).agg(
        prior_sales=("quarterly_sales", "sum"),
        prior_stores=("store_count", "sum"),
    ).reset_index()
    prior["sales_per_store_prior"] = ratio_or_nan(prior["prior_sales"], prior["prior_stores"])
    return prior[["quarter", "industry_code", "sales_per_store_prior"]]


def _group_mean(frame: pd.DataFrame, column: str, output: str) -> pd.DataFrame:
    return frame.groupby(KEYS, observed=True, sort=False)[column].mean().rename(output).reset_index()


def _merge_many(base: pd.DataFrame, additions: list[pd.DataFrame]) -> pd.DataFrame:
    result = base
    for addition in additions:
        result = result.merge(addition, on=KEYS, how="left", validate="one_to_one")
    return result


def prepare_evidence_panel(
    sales: pd.DataFrame,
    stores: pd.DataFrame,
    commercial_change: pd.DataFrame,
    quarters: list[str],
    *,
    smoothing_store_count: float = 5.0,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build a complete 20-quarter panel for combinations ever observed in sales."""
    sales_columns = [*PANEL_KEYS, "area_name", "industry_name", "당월_매출_금액"]
    store_columns = [*PANEL_KEYS, "SIMILR_INDUTY_STOR_CO", "FRC_STOR_CO", "OPBIZ_RT", "CLSBIZ_RT"]
    commercial_columns = ["quarter", "area_code", "TRDAR_CHNGE_IX", "TRDAR_CHNGE_IX_NM", "OPR_SALE_MT_AVRG", "CLS_SALE_MT_AVRG"]
    _require_columns(sales, sales_columns, "sales")
    _require_columns(stores, store_columns, "stores")
    _require_columns(commercial_change, commercial_columns, "commercial_change")
    for frame in (sales, stores, commercial_change):
        frame["quarter"] = frame["quarter"].astype("string")
        frame["area_code"] = frame["area_code"].astype("string")
    sales["industry_code"] = sales["industry_code"].astype("string")
    stores["industry_code"] = stores["industry_code"].astype("string")
    sales = sales.loc[sales["quarter"].isin(quarters), sales_columns].copy()
    stores = stores.loc[stores["quarter"].isin(quarters), store_columns].copy()
    commercial_change = commercial_change.loc[commercial_change["quarter"].isin(quarters), commercial_columns].copy()
    _assert_unique(sales, PANEL_KEYS, "sales")
    _assert_unique(stores, PANEL_KEYS, "stores")
    _assert_unique(commercial_change, ["quarter", "area_code"], "commercial_change")

    identities = (
        sales.sort_values("quarter")
        .groupby(KEYS, observed=True, sort=False)
        .tail(1)[[*KEYS, "area_name", "industry_name"]]
        .drop_duplicates(KEYS)
    )
    quarter_frame = pd.DataFrame({"quarter": pd.Series(quarters, dtype="string")})
    panel = identities.merge(quarter_frame, how="cross")
    panel = panel.merge(
        sales[PANEL_KEYS + ["당월_매출_금액"]].rename(columns={"당월_매출_금액": "quarterly_sales"}),
        on=PANEL_KEYS,
        how="left",
        validate="one_to_one",
    )
    panel["sales_observed"] = panel["quarterly_sales"].notna().astype("int8")
    store_values = stores.rename(columns={
        "SIMILR_INDUTY_STOR_CO": "store_count",
        "FRC_STOR_CO": "franchise_store_count",
        "OPBIZ_RT": "opening_rate_raw",
        "CLSBIZ_RT": "closing_rate_raw",
    })
    panel = panel.merge(store_values, on=PANEL_KEYS, how="left", validate="one_to_one")
    panel["store_observed"] = panel["store_count"].notna().astype("int8")
    for column in ("store_count", "franchise_store_count"):
        panel[column] = pd.to_numeric(panel[column], errors="coerce").clip(lower=0)
    for column in ("opening_rate_raw", "closing_rate_raw"):
        panel[column] = pd.to_numeric(panel[column], errors="coerce").div(100).clip(0, 1)
    panel = panel.merge(
        commercial_change.rename(columns={
            "TRDAR_CHNGE_IX": "commercial_change_code",
            "TRDAR_CHNGE_IX_NM": "commercial_change_name",
            "OPR_SALE_MT_AVRG": "commercial_open_months_average",
            "CLS_SALE_MT_AVRG": "commercial_close_months_average",
        }),
        on=["quarter", "area_code"],
        how="left",
        validate="many_to_one",
    )
    panel["commercial_change_observed"] = panel["commercial_change_code"].notna().astype("int8")
    sales_industries = set(identities["industry_code"])
    store_priors = _weighted_store_priors(stores.loc[stores["industry_code"].isin(sales_industries)])
    panel = panel.merge(store_priors, on=["quarter", "industry_code"], how="left", validate="many_to_one")
    store_denominator = panel["store_count"] + smoothing_store_count
    panel["smoothed_franchise_ratio"] = ratio_or_nan(
        panel["franchise_store_count"] + smoothing_store_count * panel["franchise_prior"],
        store_denominator,
    )
    panel["smoothed_opening_rate"] = ratio_or_nan(
        panel["store_count"] * panel["opening_rate_raw"] + smoothing_store_count * panel["opening_prior"],
        store_denominator,
    )
    panel["smoothed_closing_rate"] = ratio_or_nan(
        panel["store_count"] * panel["closing_rate_raw"] + smoothing_store_count * panel["closing_prior"],
        store_denominator,
    )
    sales_prior = _sales_per_store_priors(panel)
    panel = panel.merge(sales_prior, on=["quarter", "industry_code"], how="left", validate="many_to_one")
    panel["smoothed_sales_per_store"] = ratio_or_nan(
        panel["quarterly_sales"] + smoothing_store_count * panel["sales_per_store_prior"],
        store_denominator,
    )
    panel.loc[panel["sales_observed"].eq(0), "smoothed_sales_per_store"] = np.nan
    quarter_index = {quarter: index for index, quarter in enumerate(quarters)}
    panel["quarter_index"] = panel["quarter"].map(quarter_index).astype("int8")
    panel = panel.sort_values([*KEYS, "quarter_index"]).reset_index(drop=True)
    return panel, identities


def summarize_evidence(
    panel: pd.DataFrame,
    identities: pd.DataFrame,
    area_profile: pd.DataFrame,
    quarters: list[str],
) -> tuple[pd.DataFrame, dict[str, tuple[float, float]]]:
    """Aggregate the complete panel to one historical evidence row per combination."""
    observed = panel.loc[panel["sales_observed"].eq(1)].copy()
    observed["log_sales"] = np.log1p(observed["quarterly_sales"].clip(lower=0))
    quarter_index_float = observed["quarter_index"].astype("float64")
    observed["x_log_sales"] = quarter_index_float * observed["log_sales"]
    observed["x_squared"] = quarter_index_float**2
    stats = observed.groupby(KEYS, observed=True, sort=False).agg(
        observed_quarter_count=("quarterly_sales", "size"),
        first_observed_quarter=("quarter", "min"),
        latest_observed_quarter=("quarter", "max"),
        first_observed_index=("quarter_index", "min"),
        latest_observed_index=("quarter_index", "max"),
        average_sales=("quarterly_sales", "mean"),
        sales_standard_deviation=("quarterly_sales", lambda values: values.std(ddof=0)),
        sum_x=("quarter_index", "sum"),
        sum_y=("log_sales", "sum"),
        sum_xy=("x_log_sales", "sum"),
        sum_x2=("x_squared", "sum"),
    ).reset_index()
    n = stats["observed_quarter_count"].astype(float)
    slope_denominator = n * stats["sum_x2"] - stats["sum_x"] ** 2
    stats["long_term_sales_trend_slope"] = ratio_or_nan(
        n * stats["sum_xy"] - stats["sum_x"] * stats["sum_y"],
        slope_denominator,
    )
    stats["sales_coefficient_of_variation"] = ratio_or_nan(stats["sales_standard_deviation"], stats["average_sales"])
    observed_span = stats["latest_observed_index"] - stats["first_observed_index"] + 1
    stats["data_continuity"] = ratio_or_nan(stats["observed_quarter_count"], observed_span)
    stats["quarter_age"] = len(quarters) - 1 - stats["latest_observed_index"]

    latest_rows = observed.sort_values("quarter_index").groupby(KEYS, observed=True, sort=False).tail(1)
    latest_rows = latest_rows[[*KEYS, "quarterly_sales"]].rename(columns={"quarterly_sales": "latest_observed_sales"})
    panel["previous_sales"] = panel.groupby(KEYS, observed=True, sort=False)["quarterly_sales"].shift(1)
    panel["comparable_transition"] = (panel["quarterly_sales"].notna() & panel["previous_sales"].notna()).astype("int8")
    panel["decline_transition"] = (panel["comparable_transition"].eq(1) & panel["quarterly_sales"].lt(panel["previous_sales"])).astype("int8")
    decline = panel.groupby(KEYS, observed=True, sort=False).agg(
        comparable_transition_count=("comparable_transition", "sum"),
        decline_quarter_count=("decline_transition", "sum"),
    ).reset_index()
    decline["decline_quarter_ratio"] = ratio_or_nan(decline["decline_quarter_count"], decline["comparable_transition_count"])

    panel["sales_lag_4"] = panel.groupby(KEYS, observed=True, sort=False)["quarterly_sales"].shift(4)
    panel["yoy_growth_raw"] = ratio_or_nan(panel["quarterly_sales"], panel["sales_lag_4"]) - 1
    yoy = panel.loc[panel["yoy_growth_raw"].notna()].groupby(KEYS, observed=True, sort=False).tail(1)
    yoy = yoy[[*KEYS, "quarter", "yoy_growth_raw"]].rename(columns={"quarter": "yoy_reference_quarter"})

    recent = panel.loc[panel["quarter"].isin(RECENT_QUARTERS)]
    previous = panel.loc[panel["quarter"].isin(PREVIOUS_QUARTERS)]
    recent_summary = recent.groupby(KEYS, observed=True, sort=False).agg(
        recent_4q_average_sales=("quarterly_sales", "mean"),
        recent_4q_observation_count=("sales_observed", "sum"),
        recent_4q_average_sales_per_store=("smoothed_sales_per_store", "mean"),
        sample_size=("store_count", "mean"),
        recent_franchise_ratio=("smoothed_franchise_ratio", "mean"),
        opening_rate=("smoothed_opening_rate", "mean"),
        closing_rate=("smoothed_closing_rate", "mean"),
    ).reset_index()
    previous_summary = previous.groupby(KEYS, observed=True, sort=False).agg(
        previous_4q_average_sales=("quarterly_sales", "mean"),
        previous_4q_observation_count=("sales_observed", "sum"),
        previous_closing_rate=("smoothed_closing_rate", "mean"),
    ).reset_index()
    current = panel.loc[panel["quarter"].eq(quarters[-1]), [
        *KEYS, "quarterly_sales", "store_count", "commercial_change_code", "commercial_change_name",
        "commercial_open_months_average", "commercial_close_months_average", "commercial_change_observed",
    ]].rename(columns={
        "quarterly_sales": "current_quarter_sales",
        "store_count": "recent_store_count",
        "commercial_change_code": "recent_commercial_change_code",
        "commercial_change_name": "recent_commercial_change_name",
    })
    store_coverage = panel.groupby(KEYS, observed=True, sort=False)["store_observed"].sum().rename("store_observed_quarter_count").reset_index()
    zero_denominator = panel.assign(
        zero_store=((panel["sales_observed"].eq(1)) & (panel["store_count"].fillna(0).le(0))).astype("int8")
    ).groupby(KEYS, observed=True, sort=False)["zero_store"].max().rename("zero_store_denominator_flag").reset_index()

    evidence = _merge_many(
        identities.copy(),
        [stats, latest_rows, decline, yoy, recent_summary, previous_summary, current, store_coverage, zero_denominator],
    )
    evidence["recent_4q_growth_raw"] = ratio_or_nan(
        evidence["recent_4q_average_sales"], evidence["previous_4q_average_sales"]
    ) - 1
    enough_growth_data = evidence["recent_4q_observation_count"].ge(2) & evidence["previous_4q_observation_count"].ge(2)
    evidence.loc[~enough_growth_data, "recent_4q_growth_raw"] = np.nan
    evidence["net_store_growth_rate"] = evidence["opening_rate"] - evidence["closing_rate"]
    evidence["churn_rate"] = evidence["opening_rate"] + evidence["closing_rate"]
    evidence["recent_closure_rate_increase"] = evidence["closing_rate"] - evidence["previous_closing_rate"]
    evidence["closure_rate_increased_flag"] = evidence["recent_closure_rate_increase"].gt(0).astype("int8")
    evidence.loc[evidence["recent_closure_rate_increase"].isna(), "closure_rate_increased_flag"] = 0
    evidence["commercial_contraction_flag"] = evidence["recent_commercial_change_code"].eq("HL").astype("int8")

    area = area_profile.copy()
    _require_columns(area, ["quarter", "area_code", "area_size_sqm", "data_reliability", "observation_count"], "area_profile")
    area["area_code"] = area["area_code"].astype("string")
    area_summary = area.groupby("area_code", observed=True, sort=False).agg(
        area_size_sqm=("area_size_sqm", "first"),
        area_profile_data_reliability=("data_reliability", "mean"),
        area_profile_observation_count=("observation_count", "max"),
    ).reset_index()
    evidence = evidence.merge(area_summary, on="area_code", how="left", validate="many_to_one")
    evidence["area_profile_missing_flag"] = evidence["area_size_sqm"].isna().astype("int8")
    density = ratio_or_nan(evidence["recent_store_count"] * 1_000_000.0, evidence["area_size_sqm"])
    evidence["same_industry_store_density"] = density
    evidence["log_same_industry_store_density"] = np.log1p(density.clip(lower=0))
    density_rank = evidence.groupby("industry_code", observed=True)["log_same_industry_store_density"].rank(pct=True)
    store_rank = evidence.groupby("industry_code", observed=True)["recent_store_count"].rank(pct=True)
    evidence["competition_intensity"] = 0.7 * density_rank + 0.3 * store_rank

    evidence["sales_coverage"] = evidence["observed_quarter_count"] / len(quarters)
    evidence["recency_score"] = np.power(0.7, evidence["quarter_age"].clip(lower=0))
    evidence["sample_size_score"] = (evidence["sample_size"].fillna(0) / 10.0).clip(0, 1)
    evidence["store_coverage"] = evidence["store_observed_quarter_count"] / len(quarters)
    area_reliability = evidence["area_profile_data_reliability"].fillna(0)
    evidence["data_reliability"] = (
        0.25 * evidence["sales_coverage"]
        + 0.15 * evidence["data_continuity"].fillna(0)
        + 0.25 * evidence["recency_score"]
        + 0.15 * evidence["sample_size_score"]
        + 0.15 * area_reliability
        + 0.05 * evidence["store_coverage"]
    ).clip(0, 1)
    evidence["reliability_grade"] = pd.cut(
        evidence["data_reliability"],
        bins=[-np.inf, 0.5, 0.7, 0.85, np.inf],
        labels=["D", "C", "B", "A"],
        right=False,
    ).astype("string")
    evidence["stale_observation_flag"] = evidence["quarter_age"].ge(4).astype("int8")
    evidence["current_sales_missing_flag"] = evidence["current_quarter_sales"].isna().astype("int8")
    evidence["recent_4q_sales_missing_flag"] = evidence["recent_4q_average_sales"].isna().astype("int8")
    evidence["recent_4q_partial_observation_flag"] = evidence["recent_4q_observation_count"].lt(4).astype("int8")
    evidence["yoy_growth_missing_flag"] = evidence["yoy_growth_raw"].isna().astype("int8")
    evidence["recent_growth_missing_flag"] = evidence["recent_4q_growth_raw"].isna().astype("int8")
    evidence["recent_store_missing_flag"] = evidence["recent_store_count"].isna().astype("int8")
    evidence["commercial_change_missing_flag"] = evidence["commercial_change_observed"].fillna(0).eq(0).astype("int8")

    clip_bounds: dict[str, tuple[float, float]] = {}
    evidence["yoy_growth_rate"], evidence["yoy_growth_clipped_flag"], clip_bounds["yoy_growth_rate"] = _clip_series(
        evidence["yoy_growth_raw"], lower_quantile=0.01, upper_quantile=0.99, hard_lower=-0.95, hard_upper=5.0
    )
    evidence["recent_4q_growth_rate"], evidence["recent_4q_growth_clipped_flag"], clip_bounds["recent_4q_growth_rate"] = _clip_series(
        evidence["recent_4q_growth_raw"], lower_quantile=0.01, upper_quantile=0.99, hard_lower=-0.95, hard_upper=5.0
    )
    evidence["sales_coefficient_of_variation"], evidence["sales_cv_clipped_flag"], clip_bounds["sales_coefficient_of_variation"] = _clip_series(
        evidence["sales_coefficient_of_variation"], lower_quantile=0.0, upper_quantile=0.995, hard_lower=0.0
    )
    evidence["long_term_sales_trend_slope"], evidence["long_term_trend_clipped_flag"], clip_bounds["long_term_sales_trend_slope"] = _clip_series(
        evidence["long_term_sales_trend_slope"], lower_quantile=0.005, upper_quantile=0.995, hard_lower=-2.0, hard_upper=2.0
    )
    evidence["recent_4q_average_sales_per_store"], evidence["sales_per_store_clipped_flag"], clip_bounds["recent_4q_average_sales_per_store"] = _clip_series(
        evidence["recent_4q_average_sales_per_store"], lower_quantile=0.0, upper_quantile=0.995, hard_lower=0.0
    )
    evidence = evidence.drop(columns=[
        "sum_x", "sum_y", "sum_xy", "sum_x2", "first_observed_index", "latest_observed_index",
        "sales_standard_deviation", "average_sales", "yoy_growth_raw", "recent_4q_growth_raw",
    ])
    evidence["area_code"] = evidence["area_code"].astype("string")
    evidence["industry_code"] = evidence["industry_code"].astype("string")
    evidence = evidence.sort_values(KEYS).reset_index(drop=True)
    _assert_unique(evidence, KEYS, "area_industry_evidence")
    return evidence, clip_bounds


def build_evidence_dictionary(
    evidence: pd.DataFrame,
    clip_bounds: dict[str, tuple[float, float]],
) -> pd.DataFrame:
    """Describe evidence output columns and missing-value semantics."""
    rows: list[dict[str, Any]] = []
    for column in evidence.columns:
        if column in KEYS:
            role, group = "key", "key"
        elif column in {"area_name", "industry_name", "first_observed_quarter", "latest_observed_quarter", "yoy_reference_quarter", "recent_commercial_change_code", "recent_commercial_change_name", "reliability_grade"}:
            role, group = "metadata", "identity_or_quality"
        elif column.endswith(("_flag", "_observed")) or column in {"observed_quarter_count", "store_observed_quarter_count", "data_continuity", "quarter_age", "sales_coverage", "recency_score", "sample_size_score", "store_coverage", "data_reliability", "area_profile_data_reliability", "area_profile_observation_count"}:
            role, group = "quality", "reliability"
        elif "sales" in column or "growth" in column or "decline" in column or "trend" in column or "variation" in column:
            role, group = "feature", "sales_performance"
        elif any(token in column for token in ("store", "franchise", "competition")):
            role, group = "feature", "competition"
        elif any(token in column for token in ("opening", "closing", "closure", "churn", "commercial")):
            role, group = "feature", "risk"
        else:
            role, group = "feature", "support"
        lower, upper = clip_bounds.get(column, (np.nan, np.nan))
        missing_policy = "NaN retained with an explicit missing/partial/stale flag" if pd.api.types.is_numeric_dtype(evidence[column]) else "unknown is not converted to zero"
        rows.append({
            "feature": column,
            "group": group,
            "role": role,
            "dtype": str(evidence[column].dtype),
            "description": "historical observed evidence; no future-sales prediction",
            "formula": "see src/features/area_industry_evidence.py",
            "missing_policy": missing_policy,
            "clip_lower": lower,
            "clip_upper": upper,
        })
    return pd.DataFrame(rows)


def build_validation_report(evidence: pd.DataFrame) -> pd.DataFrame:
    """Create grain, denominator, reliability, missingness, and distribution checks."""
    numeric = evidence.select_dtypes(include="number")
    duplicate_rows = int(evidence.duplicated(KEYS, keep=False).sum())
    inf_count = int(np.isinf(numeric.to_numpy(dtype=float)).sum())
    checks = [
        ("combination_rows", len(evidence), "INFO", "sales-observed area × industry combinations"),
        ("area_count", evidence["area_code"].nunique(), "INFO", "unique area_code"),
        ("industry_count", evidence["industry_code"].nunique(), "INFO", "sales industry code system"),
        ("grain_duplicate_rows", duplicate_rows, "PASS" if duplicate_rows == 0 else "FAIL", "area_code × industry_code"),
        ("infinite_value_count", inf_count, "PASS" if inf_count == 0 else "FAIL", "numeric columns"),
        ("zero_store_denominator_combinations", int(evidence["zero_store_denominator_flag"].sum()), "INFO", "smoothing applied; raw zero retained as flag"),
        ("stale_combination_count", int(evidence["stale_observation_flag"].sum()), "INFO", "quarter_age >= 4"),
        ("current_sales_missing_count", int(evidence["current_sales_missing_flag"].sum()), "INFO", "not interpreted as zero"),
        ("yoy_growth_clipped_count", int(evidence["yoy_growth_clipped_flag"].sum()), "INFO", "1%/99% and hard bounds"),
        ("recent_growth_clipped_count", int(evidence["recent_4q_growth_clipped_flag"].sum()), "INFO", "1%/99% and hard bounds"),
        ("long_term_trend_clipped_count", int(evidence["long_term_trend_clipped_flag"].sum()), "INFO", "0.5%/99.5% and hard bounds"),
        ("sales_per_store_clipped_count", int(evidence["sales_per_store_clipped_flag"].sum()), "INFO", "upper 99.5% bound"),
    ]
    rows: list[dict[str, Any]] = [
        {"record_type": "global_check", "name": name, "status": status, "value": value, "details": details}
        for name, value, status, details in checks
    ]
    for grade, count in evidence["reliability_grade"].value_counts(dropna=False).sort_index().items():
        rows.append({"record_type": "reliability_grade", "name": str(grade), "status": "INFO", "value": int(count), "details": "combination count"})
    for column in numeric.columns:
        series = numeric[column]
        description = series.describe(percentiles=[0.01, 0.05, 0.5, 0.95, 0.99])
        rows.append({
            "record_type": "feature_summary",
            "name": column,
            "status": "WARNING" if series.nunique(dropna=True) <= 1 else "PASS",
            "value": np.nan,
            "details": "constant feature" if series.nunique(dropna=True) <= 1 else "",
            "count": int(series.notna().sum()),
            "missing_count": int(series.isna().sum()),
            "missing_rate": float(series.isna().mean()),
            "inf_count": int(np.isinf(series.to_numpy(dtype=float)).sum()),
            "unique_count": int(series.nunique(dropna=True)),
            "mean": float(description.get("mean", np.nan)),
            "std": float(description.get("std", np.nan)),
            "min": float(description.get("min", np.nan)),
            "p01": float(description.get("1%", np.nan)),
            "p05": float(description.get("5%", np.nan)),
            "median": float(description.get("50%", np.nan)),
            "p95": float(description.get("95%", np.nan)),
            "p99": float(description.get("99%", np.nan)),
            "max": float(description.get("max", np.nan)),
        })
    return pd.DataFrame(rows)


def build_area_industry_evidence(
    *,
    project_root: Path = PROJECT_ROOT,
    interim_dir: Path | None = None,
    processed_dir: Path | None = None,
    output_dir: Path | None = None,
    smoothing_store_count: float = 5.0,
) -> EvidenceResult:
    """Build and save 2021Q1~2025Q4 historical area-industry evidence."""
    config = load_datasets_config(project_root / "config/datasets.yaml")
    period = config["analysis_period"]
    quarters = [str(value) for value in generate_quarters(period["start_quarter"], period["end_quarter"])]
    if len(quarters) != 20 or quarters[0] != "20211" or quarters[-1] != "20254":
        raise ValueError(f"evidence 기간은 정확히 20211~20254여야 합니다: {quarters}")
    interim = interim_dir or (project_root / "data/interim" if project_root != PROJECT_ROOT else INTERIM_DIR)
    processed = processed_dir or (project_root / "data/processed" if project_root != PROJECT_ROOT else PROCESSED_DIR)
    tables = output_dir or (project_root / "outputs/tables" if project_root != PROJECT_ROOT else OUTPUT_DIR / "tables")
    paths = {
        "sales": interim / "sales.parquet",
        "stores": interim / "stores.parquet",
        "commercial_change": interim / "commercial_change.parquet",
        "area_profile": processed / "area_profile.parquet",
    }
    for name, path in paths.items():
        if not path.exists():
            raise FileNotFoundError(f"[{name}] 입력 파일이 없습니다: {path}")
    sales = pd.read_parquet(paths["sales"])
    stores = pd.read_parquet(paths["stores"])
    commercial = pd.read_parquet(paths["commercial_change"])
    area_profile = pd.read_parquet(paths["area_profile"])
    panel, identities = prepare_evidence_panel(
        sales, stores, commercial, quarters, smoothing_store_count=smoothing_store_count
    )
    evidence, clip_bounds = summarize_evidence(panel, identities, area_profile, quarters)
    dictionary = build_evidence_dictionary(evidence, clip_bounds)
    validation = build_validation_report(evidence)
    stale_columns = [
        "area_code", "area_name", "industry_code", "industry_name", "latest_observed_quarter",
        "quarter_age", "observed_quarter_count", "data_continuity", "data_reliability",
        "reliability_grade", "current_sales_missing_flag",
    ]
    stale = evidence.loc[evidence["stale_observation_flag"].eq(1), stale_columns].sort_values(
        ["quarter_age", "data_reliability", "area_code", "industry_code"],
        ascending=[False, True, True, True],
    )
    failed = validation.loc[(validation["record_type"] == "global_check") & (validation["status"] == "FAIL")]
    if not failed.empty:
        raise ValueError(f"area-industry evidence 검증 실패: {failed[['name', 'details']].to_dict('records')}")
    processed.mkdir(parents=True, exist_ok=True)
    tables.mkdir(parents=True, exist_ok=True)
    evidence.to_parquet(processed / "area_industry_evidence.parquet", index=False)
    dictionary.to_csv(tables / "area_industry_evidence_dictionary.csv", index=False, encoding="utf-8-sig")
    validation.to_csv(tables / "area_industry_evidence_validation.csv", index=False, encoding="utf-8-sig")
    stale.to_csv(tables / "stale_industry_combinations.csv", index=False, encoding="utf-8-sig")
    return EvidenceResult(evidence, dictionary, validation, stale)
